### ISSUE TITLE
Custom EEs and -m stdout provide no output.

### ISSUE THREAD

**Issue by dallasspohn** [ansible/ansible-navigator#625]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If I run the playbook with the custom EE, the playbook succeeds without any output to stdout.
ansible-navigator run --eei localhost/ee-motd-minimal --pp never -i inventory -m stdout motd-test.yml
Exit code of 0, everything completes successfully, but no playbook output.

##### ANSIBLE-NAVIGATOR VERSION

```
[student@workstation builder-validate]$ ansible-navigator --version
ansible-navigator 1.0.0

```

##### CONFIGURATION
cat ansible-navigator.yml 
---
ansible-navigator:
  ansible:
    config: ./ansible.cfg

  execution-environment:
    image: ee-supported-rhel8:2.0
    pull-policy: missing

##### STEPS TO REPRODUCE

ansible-navigator run --eei localhost/ee-motd-minimal --pp never -i inventory -m stdout motd-test.yml

##### EXPECTED RESULTS

Should see stdout

##### ACTUAL RESULTS

nothing

**Comment by cidrblock** [comment]
@dallasspohn Ty for the issue

would you mind running it again with `--ll debug --la false` and provide the log output here?

the log details should give us some indication of what's going on behind the scenes

**Comment by dallasspohn** [comment]
@cidrblock Here is the output.
```

[student@workstation builder-validate]$ ansible-navigator run --eei localhost/ee-motd-minimal --pp never -i inventory -m stdout motd-test.yml
[student@workstation builder-validate]$ ansible-navigator run --eei localhost/ee-motd-minimal --pp never -i inventory -m stdout motd-test.yml --ll debug --la false 
[student@workstation builder-validate]$ 
```

**Comment by cidrblock** [comment]
Sorry, I meant the contents of the log file :)

**Comment by jmighion** [comment]
@IPvSean JFYI

**Comment by dallasspohn** [comment]
[student@workstation builder-validate]$ cat ansible-navigator.log 
211119205701.446 INFO 'ansible_navigator.setup_logger' New ansible-navigator instance, logging initialized
211119205701.446 INFO 'ansible_navigator.setup_logger' New ansible-runner instance, logging initialized
211119205701.446 DEBUG 'ansible_navigator.main' Share directory '/usr/lib/python3.8/site-packages/share/ansible_navigator' not found (development path)
211119205701.446 DEBUG 'ansible_navigator.main' Share directory '/home/student/.local/share/ansible_navigator' not found (userbase)
211119205701.446 DEBUG 'ansible_navigator.main' Share directory '/usr/share/ansible_navigator' found (sys.prefix)
211119205701.446 DEBUG 'ansible_navigator.main' Default collection_doc_cache_path set to: /home/student/.cache/ansible-navigator/collection_doc_cache.db
211119205701.446 DEBUG 'ansible_navigator.main' EDITOR environment variable not set
211119205701.446 DEBUG 'ansible_navigator.main' Default editor_command set to: vi +{line_number} {filename}
211119205701.446 DEBUG 'ansible_navigator.main' No config file set by ANSIBLE_NAVIGATOR_CONFIG
211119205701.446 DEBUG 'ansible_navigator.main' Looking in /home/student
211119205701.447 DEBUG 'ansible_navigator.main' Looking for '/home/student/.ansible-navigator.yml', '/home/student/.ansible-navigator.yaml' and '/home/student/.ansible-navigator.json'
211119205701.447 DEBUG 'ansible_navigator.main' Found 0: 
211119205701.447 DEBUG 'ansible_navigator.main' Looking in /home/student/builder-validate
211119205701.447 DEBUG 'ansible_navigator.main' Looking for '/home/student/builder-validate/ansible-navigator.yml', '/home/student/builder-validate/ansible-navigator.yaml' and '/home/student/builder-validate/ansible-navigator.json'
211119205701.447 DEBUG 'ansible_navigator.main' Found 1: '/home/student/builder-validate/ansible-navigator.yml'
211119205701.447 DEBUG 'ansible_navigator.main' All found 1: '/home/student/builder-validate/ansible-navigator.yml'
211119205701.447 DEBUG 'ansible_navigator.main' Using: /home/student/builder-validate/ansible-navigator.yml
211119205701.447 DEBUG 'ansible_navigator.main' Using settings file at /home/student/builder-validate/ansible-navigator.yml in search path
211119205701.447 DEBUG 'ansible_navigator.main' Command provided: 'run --eei localhost/ee-motd-minimal --pp never -i inventory -m stdout motd-test.yml --ll debug --la false'
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.ansible-runner.artifact-dir not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.ansible-runner.rotate-artifacts-count not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.ansible-runner.timeout not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.app not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.ansible.cmdline not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.collection-doc-cache-path not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.execution-environment.container-engine not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.color.enable not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.editor.command not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.editor.console not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.execution-environment.enabled not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.execution-environment.volume-mounts not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.help-config not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.help-doc not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.help-inventory not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.help-playbook not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.ansible.inventories not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.inventory-columns not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.logging.append not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.logging.file not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.logging.level not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.mode not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.color.osc4 not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.execution-environment.environment-variables.pass not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.ansible.playbook not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.playbook-artifact.enable not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.playbook-artifact.replay not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.playbook-artifact.save-as not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.documentation.plugin.name not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.documentation.plugin.type not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' ansible-navigator.execution-environment.environment-variables.set not found in settings file
211119205701.447 DEBUG 'ansible_navigator.main' Completed post processing for ansible_runner_artifact_dir. (changed=False)
211119205701.447 DEBUG 'ansible_navigator.main' Completed post processing for ansible_runner_rotate_artifacts_count. (changed=False)
211119205701.447 DEBUG 'ansible_navigator.main' Completed post processing for ansible_runner_timeout. (changed=False)
211119205701.447 DEBUG 'ansible_navigator.main' Completed post processing for cmdline. (changed=False)
211119205701.447 DEBUG 'ansible_navigator.main' Completed post processing for collection_doc_cache_path. (changed=False)
211119205701.447 DEBUG 'ansible_navigator.main' Completed post processing for container_engine. (changed=True)
211119205701.447 DEBUG 'ansible_navigator.main'  before: 'auto'
211119205701.448 DEBUG 'ansible_navigator.main'  after: 'podman'
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for display_color. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for editor_console. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for execution_environment. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for execution_environment_image. (changed=True)
211119205701.448 DEBUG 'ansible_navigator.main'  before: 'localhost/ee-motd-minimal'
211119205701.448 DEBUG 'ansible_navigator.main'  after: 'localhost/ee-motd-minimal:latest'
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for execution_environment_volume_mounts. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for help_config. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for help_doc. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for help_inventory. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for help_playbook. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for inventory. (changed=True)
211119205701.448 DEBUG 'ansible_navigator.main'  before: '[['inventory']]'
211119205701.448 DEBUG 'ansible_navigator.main'  after: '['/home/student/builder-validate/inventory']'
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for inventory_column. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for log_append. (changed=True)
211119205701.448 DEBUG 'ansible_navigator.main'  before: 'false'
211119205701.448 DEBUG 'ansible_navigator.main'  after: 'False'
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for log_file. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for mode. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for osc4. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for pass_environment_variable. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for playbook. (changed=True)
211119205701.448 DEBUG 'ansible_navigator.main'  before: 'motd-test.yml'
211119205701.448 DEBUG 'ansible_navigator.main'  after: '/home/student/builder-validate/motd-test.yml'
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for playbook_artifact_enable. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for playbook_artifact_replay. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for plugin_name. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Completed post processing for set_environment_variable. (changed=False)
211119205701.448 DEBUG 'ansible_navigator.main' Collection doc cache not mounted
211119205701.448 DEBUG 'ansible_navigator.main' Collection doc cache: 'path' is '/home/student/.cache/ansible-navigator/collection_doc_cache.db'
211119205701.448 DEBUG 'ansible_navigator.main' Collection doc cache: 'current version' is '1.0'
211119205701.448 DEBUG 'ansible_navigator.main' Collection doc cache not attached to args.internals
211119205701.448 DEBUG 'ansible_navigator.main' Running with ansible_runner_artifact_dir as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.448 DEBUG 'ansible_navigator.main' Running with ansible_runner_rotate_artifacts_count as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.448 DEBUG 'ansible_navigator.main' Running with ansible_runner_timeout as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.448 DEBUG 'ansible_navigator.main' Running with app as 'run' (str/cli parameters)
211119205701.448 DEBUG 'ansible_navigator.main' Running with cmdline as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.448 DEBUG 'ansible_navigator.main' Running with collection_doc_cache_path as '/home/student/.cache/ansible-navigator/collection_doc_cache.db' (str/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with config as './ansible.cfg' (str/user provided configuration file)
211119205701.448 DEBUG 'ansible_navigator.main' Running with container_engine as 'podman' (str/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with display_color as 'True' (bool/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with editor_command as 'vi +{line_number} {filename}' (str/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with editor_console as 'True' (bool/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with execution_environment as 'True' (bool/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with execution_environment_image as 'localhost/ee-motd-minimal:latest' (str/cli parameters)
211119205701.448 DEBUG 'ansible_navigator.main' Running with execution_environment_volume_mounts as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.448 DEBUG 'ansible_navigator.main' Running with help_config as 'False' (bool/default configuration value)
211119205701.448 DEBUG 'ansible_navigator.main' Running with help_doc as 'False' (bool/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with help_inventory as 'False' (bool/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with help_playbook as 'False' (bool/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with inventory as '['/home/student/builder-validate/inventory']' (list/cli parameters)
211119205701.449 DEBUG 'ansible_navigator.main' Running with inventory_column as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.449 DEBUG 'ansible_navigator.main' Running with log_append as 'False' (bool/cli parameters)
211119205701.449 DEBUG 'ansible_navigator.main' Running with log_file as '/home/student/builder-validate/ansible-navigator.log' (str/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with log_level as 'debug' (str/cli parameters)
211119205701.449 DEBUG 'ansible_navigator.main' Running with mode as 'stdout' (str/cli parameters)
211119205701.449 DEBUG 'ansible_navigator.main' Running with osc4 as 'True' (bool/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with pass_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.449 DEBUG 'ansible_navigator.main' Running with playbook as '/home/student/builder-validate/motd-test.yml' (str/cli parameters)
211119205701.449 DEBUG 'ansible_navigator.main' Running with playbook_artifact_enable as 'True' (bool/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with playbook_artifact_replay as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.449 DEBUG 'ansible_navigator.main' Running with playbook_artifact_save_as as '{playbook_dir}/{playbook_name}-artifact-{ts_utc}.json' (str/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with plugin_name as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.449 DEBUG 'ansible_navigator.main' Running with plugin_type as 'module' (str/default configuration value)
211119205701.449 DEBUG 'ansible_navigator.main' Running with pull_policy as 'never' (str/cli parameters)
211119205701.449 DEBUG 'ansible_navigator.main' Running with set_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
211119205701.449 INFO 'ansible_navigator.image_manager.puller._log_message' Image tag is: latest
211119205701.616 DEBUG 'ansible_navigator.actions.run.run_stdout' playbook requested in interactive mode
211119205701.617 DEBUG 'ansible_navigator.runner.api._set_private_data_directory' private data dir not user provided, used tmp location: /tmp/ansible-navigator_41l8s2q6
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: container_image:localhost/ee-motd-minimal:latest
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: process_isolation_executable:podman
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: process_isolation:True
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: container_volume_mounts:None
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: container_options:None
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: container_workdir:None
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: private_data_dir:/tmp/ansible-navigator_41l8s2q6
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: json_mode:True
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: quiet:True
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: cancel_callback:<bound method BaseRunner.runner_cancelled_callback of <ansible_navigator.runner.api.CommandRunnerAsync object at 0x7f279245f850>>
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: finished_callback:<bound method BaseRunner.runner_finished_callback of <ansible_navigator.runner.api.CommandRunnerAsync object at 0x7f279245f850>>
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: artifacts_handler:<bound method BaseRunner.runner_artifacts_handler of <ansible_navigator.runner.api.CommandRunnerAsync object at 0x7f279245f850>>
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: timeout:None
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: envvars:{}
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: host_cwd:/home/student/builder-validate/
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: executable_cmd:ansible-playbook
211119205701.618 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: cmdline_args:['/home/student/builder-validate/motd-test.yml', '-i', '/home/student/builder-validate/inventory']
211119205701.619 DEBUG 'ansible-runner._handle_command_wrap' containerization enabled
211119205701.619 DEBUG 'ansible-runner.wrap_args_for_containerization' container engine invocation: podman run --rm --tty --interactive -v /home/student/builder-validate/:/home/student/builder-validate/ --workdir /home/student/builder-validate -v /tmp/ssh-DMaEZdzEwS/:/tmp/ssh-DMaEZdzEwS/ -e SSH_AUTH_SOCK=/tmp/ssh-DMaEZdzEwS/agent.73317 -v /home/student/.ssh/:/home/runner/.ssh/ --group-add=root --userns=keep-id --ipc=host -v /tmp/ansible-navigator_41l8s2q6/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator_41l8s2q6/:/runner/:Z --env-file /tmp/ansible-navigator_41l8s2q6/artifacts/622b8546-3ef2-49e6-bfe4-8616f2568e02/env.list --quiet --name ansible_runner_622b8546-3ef2-49e6-bfe4-8616f2568e02 localhost/ee-motd-minimal:latest ansible-playbook /home/student/builder-validate/motd-test.yml -i /home/student/builder-validate/inventory
211119205701.619 DEBUG 'ansible-runner._handle_command_wrap' command: podman run --rm --tty --interactive -v /home/student/builder-validate/:/home/student/builder-validate/ --workdir /home/student/builder-validate -v /tmp/ssh-DMaEZdzEwS/:/tmp/ssh-DMaEZdzEwS/ -e SSH_AUTH_SOCK=/tmp/ssh-DMaEZdzEwS/agent.73317 -v /home/student/.ssh/:/home/runner/.ssh/ --group-add=root --userns=keep-id --ipc=host -v /tmp/ansible-navigator_41l8s2q6/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator_41l8s2q6/:/runner/:Z --env-file /tmp/ansible-navigator_41l8s2q6/artifacts/622b8546-3ef2-49e6-bfe4-8616f2568e02/env.list --quiet --name ansible_runner_622b8546-3ef2-49e6-bfe4-8616f2568e02 localhost/ee-motd-minimal:latest ansible-playbook /home/student/builder-validate/motd-test.yml -i /home/student/builder-validate/inventory
211119205701.620 DEBUG 'ansible_navigator.actions.run_playbook._run_runner' runner requested to start
211119205705.017 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'a5592625-a6b5-456e-8f0a-0568d74eca36', 'counter': 1, 'stdout': '', 'start_line': 0, 'end_line': 0, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.017789'}
211119205705.023 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'a5592625-a6b5-456e-8f0a-0568d74eca36', 'counter': 1, 'stdout': '', 'start_line': 0, 'end_line': 0, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.017789'}
211119205705.024 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205705.024 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'ea5f4520-7e90-4256-dacd-000000000007', 'counter': 2, 'stdout': '\r\nPLAY [Test banner role from exercise.motd collection] **************************', 'start_line': 0, 'end_line': 2, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.024184'}
211119205705.034 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'ea5f4520-7e90-4256-dacd-000000000007', 'counter': 2, 'stdout': '\r\nPLAY [Test banner role from exercise.motd collection] **************************', 'start_line': 0, 'end_line': 2, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.024184'}
211119205705.035 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205705.061 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'ea5f4520-7e90-4256-dacd-000000000011', 'counter': 3, 'stdout': '\r\nTASK [Gathering Facts] *********************************************************', 'start_line': 2, 'end_line': 4, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.061235'}
211119205705.066 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'ea5f4520-7e90-4256-dacd-000000000011', 'counter': 3, 'stdout': '\r\nTASK [Gathering Facts] *********************************************************', 'start_line': 2, 'end_line': 4, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.061235'}
211119205705.067 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205705.072 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '4f28f565-4533-4bc9-a7ed-30fb128dd171', 'counter': 4, 'stdout': '', 'start_line': 4, 'end_line': 4, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.072360'}
211119205705.078 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '4f28f565-4533-4bc9-a7ed-30fb128dd171', 'counter': 4, 'stdout': '', 'start_line': 4, 'end_line': 4, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.072360'}
211119205705.078 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205705.111 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '976aadae-de7f-4542-9b7d-7984e4d27c51', 'counter': 5, 'stdout': '', 'start_line': 4, 'end_line': 4, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.111174'}
211119205705.116 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '976aadae-de7f-4542-9b7d-7984e4d27c51', 'counter': 5, 'stdout': '', 'start_line': 4, 'end_line': 4, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:05.111174'}
211119205705.116 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205706.712 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'c29d5482-1df9-4e80-b793-de38cda6d348', 'counter': 6, 'stdout': '\x1b[0;32mok: [serverd]\x1b[0m', 'start_line': 4, 'end_line': 5, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.712929'}
211119205706.718 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'c29d5482-1df9-4e80-b793-de38cda6d348', 'counter': 6, 'stdout': '\x1b[0;32mok: [serverd]\x1b[0m', 'start_line': 4, 'end_line': 5, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.712929'}
211119205706.718 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205706.750 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '6ff79c58-d31d-4335-942c-ac63225c875f', 'counter': 7, 'stdout': '\x1b[0;32mok: [serverc]\x1b[0m', 'start_line': 5, 'end_line': 6, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.750647'}
211119205706.756 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '6ff79c58-d31d-4335-942c-ac63225c875f', 'counter': 7, 'stdout': '\x1b[0;32mok: [serverc]\x1b[0m', 'start_line': 5, 'end_line': 6, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.750647'}
211119205706.756 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205706.782 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'ea5f4520-7e90-4256-dacd-00000000000c', 'counter': 8, 'stdout': '\r\nTASK [exercise.motd.banner : Ensure /etc/motd.d/ exists] ***********************', 'start_line': 6, 'end_line': 8, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.782730'}
211119205706.783 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'ea5f4520-7e90-4256-dacd-00000000000c', 'counter': 8, 'stdout': '\r\nTASK [exercise.motd.banner : Ensure /etc/motd.d/ exists] ***********************', 'start_line': 6, 'end_line': 8, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.782730'}
211119205706.783 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205706.790 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'f146242c-4893-4af7-9056-5ee84ee79ff2', 'counter': 9, 'stdout': '', 'start_line': 8, 'end_line': 8, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.790323'}
211119205706.795 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'f146242c-4893-4af7-9056-5ee84ee79ff2', 'counter': 9, 'stdout': '', 'start_line': 8, 'end_line': 8, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.790323'}
211119205706.795 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205706.816 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '88ce2c95-c4b1-4a92-b697-51fcab8007ee', 'counter': 10, 'stdout': '', 'start_line': 8, 'end_line': 8, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.816861'}
211119205706.822 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '88ce2c95-c4b1-4a92-b697-51fcab8007ee', 'counter': 10, 'stdout': '', 'start_line': 8, 'end_line': 8, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:06.816861'}
211119205706.822 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205707.364 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '42c11abd-a7f7-4c23-844a-ecba4689ccc0', 'counter': 11, 'stdout': '\x1b[0;32mok: [serverd]\x1b[0m', 'start_line': 8, 'end_line': 9, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.364936'}
211119205707.370 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '42c11abd-a7f7-4c23-844a-ecba4689ccc0', 'counter': 11, 'stdout': '\x1b[0;32mok: [serverd]\x1b[0m', 'start_line': 8, 'end_line': 9, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.364936'}
211119205707.370 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205707.386 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '064c3ac7-0ee3-44e4-a31b-2171ca7d41e0', 'counter': 12, 'stdout': '\x1b[0;32mok: [serverc]\x1b[0m', 'start_line': 9, 'end_line': 10, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.386596'}
211119205707.392 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '064c3ac7-0ee3-44e4-a31b-2171ca7d41e0', 'counter': 12, 'stdout': '\x1b[0;32mok: [serverc]\x1b[0m', 'start_line': 9, 'end_line': 10, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.386596'}
211119205707.392 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205707.406 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': 'ea5f4520-7e90-4256-dacd-00000000000d', 'counter': 13, 'stdout': '\r\nTASK [exercise.motd.banner : Create custom motd banner] ************************', 'start_line': 10, 'end_line': 12, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.406636'}
211119205707.414 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': 'ea5f4520-7e90-4256-dacd-00000000000d', 'counter': 13, 'stdout': '\r\nTASK [exercise.motd.banner : Create custom motd banner] ************************', 'start_line': 10, 'end_line': 12, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.406636'}
211119205707.414 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205707.419 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '5e16e64b-f74a-4112-8197-bbc6fc1322a8', 'counter': 14, 'stdout': '', 'start_line': 12, 'end_line': 12, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.419868'}
211119205707.425 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '5e16e64b-f74a-4112-8197-bbc6fc1322a8', 'counter': 14, 'stdout': '', 'start_line': 12, 'end_line': 12, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.419868'}
211119205707.425 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205707.451 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '266fffc2-9eef-44c8-a6f5-73dc6bc32131', 'counter': 15, 'stdout': '', 'start_line': 12, 'end_line': 12, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.451766'}
211119205707.457 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '266fffc2-9eef-44c8-a6f5-73dc6bc32131', 'counter': 15, 'stdout': '', 'start_line': 12, 'end_line': 12, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:07.451766'}
211119205707.457 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205708.480 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '7e46ba26-648c-4e61-b3dd-ec215fdbd099', 'counter': 16, 'stdout': '\x1b[0;32mok: [serverd]\x1b[0m', 'start_line': 12, 'end_line': 13, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:08.480856'}
211119205708.486 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '7e46ba26-648c-4e61-b3dd-ec215fdbd099', 'counter': 16, 'stdout': '\x1b[0;32mok: [serverd]\x1b[0m', 'start_line': 12, 'end_line': 13, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:08.480856'}
211119205708.486 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205708.507 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '1631c4dd-6c4d-438b-94f7-c4b1d718b4be', 'counter': 17, 'stdout': '\x1b[0;32mok: [serverc]\x1b[0m', 'start_line': 13, 'end_line': 14, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:08.507671'}
211119205708.513 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '1631c4dd-6c4d-438b-94f7-c4b1d718b4be', 'counter': 17, 'stdout': '\x1b[0;32mok: [serverc]\x1b[0m', 'start_line': 13, 'end_line': 14, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:08.507671'}
211119205708.513 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205708.534 DEBUG 'ansible_navigator.runner.api._event_handler' ansible-runner event handle: {'uuid': '3a162b9e-392d-454f-99dc-a6b04ef99be8', 'counter': 18, 'stdout': '\r\nPLAY RECAP *********************************************************************\r\n\x1b[0;32mserverc\x1b[0m                    : \x1b[0;32mok=3   \x1b[0m changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   \r\n\x1b[0;32mserverd\x1b[0m                    : \x1b[0;32mok=3   \x1b[0m changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   \r\n', 'start_line': 14, 'end_line': 19, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:08.534554'}
211119205708.540 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'uuid': '3a162b9e-392d-454f-99dc-a6b04ef99be8', 'counter': 18, 'stdout': '\r\nPLAY RECAP *********************************************************************\r\n\x1b[0;32mserverc\x1b[0m                    : \x1b[0;32mok=3   \x1b[0m changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   \r\n\x1b[0;32mserverd\x1b[0m                    : \x1b[0;32mok=3   \x1b[0m changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   \r\n', 'start_line': 14, 'end_line': 19, 'runner_ident': '622b8546-3ef2-49e6-bfe4-8616f2568e02', 'created': '2021-11-19T20:57:08.534554'}
211119205708.540 DEBUG 'ansible_navigator.actions.run_playbook._dequeue' Drained 1 events
211119205708.941 DEBUG 'ansible_navigator.runner.api.runner_artifacts_handler' ansible-runner artifact_dir set to: '/tmp/ansible-navigator_41l8s2q6/artifacts/622b8546-3ef2-49e6-bfe4-8616f2568e02'
211119205708.947 DEBUG 'ansible_navigator.actions.run_playbook.write_artifact' Formatted artifact file name set to /home/student/builder-validate/motd-test-artifact-2021-11-19T20:57:08.947181+00:00.json
211119205708.947 DEBUG 'ansible_navigator.actions.run_playbook.write_artifact' Resolved artifact file name set to /home/student/builder-validate/motd-test-artifact-2021-11-19T20:57:08.947181+00:00.json
211119205708.947 INFO 'ansible_navigator.actions.run_playbook.write_artifact' Saved artifact as /home/student/builder-validate/motd-test-artifact-2021-11-19T20:57:08.947181+00:00.json
211119205708.948 DEBUG 'ansible_navigator.actions.run_playbook.run_stdout' runner finished
[student@workstation builder-validate]$

**Comment by cidrblock** [comment]
@dallasspohn thanks! 

One issue that caused these unhandled runner messages was fixed in the latest release of ansible runner.

Can you check your version of that package?

One other way to test is use a brand new venv and install ansible navigator in it and try with that


LMK, brad

**Comment by dallasspohn** [comment]
Hi Brad, Apologies, I have been out of the office.

I created a new venv and reinstalled ansible-navigator on it. Still shows no output.
(labs) student @ ~/builder-validate
└─ $ ansible-runner --version
2.0.2

```
(labs) student @ ~/builder-validate
└─ $ cat motd-test-artifact-2021-12-08T20\:01\:07.775203+00\:00.json 
{
    "version": "1.0.0",
    "plays": [],
    "stdout": [],
    "status": "successful",
    "status_color": 10
}
```

**Comment by dallasspohn** [comment]
Any updates?

**Comment by dallasspohn** [comment]
@IPvSean Any information on your end about this?

**Comment by dallasspohn** [comment]
@cidrblock I will bump this just as a gentle reminder.

**Comment by cidrblock** [comment]
sorry @dallasspohn   I will have a chance to look into this next week.

**Comment by cidrblock** [comment]
@dallasspohn 

Can you check the log file (`--ll debug``) after a run using the new venv and confirm whther or not the "unhandled" messages are there?

Also- can you provide a pip freeze from that venv?

The latest version of runner is 2.1.1, so I'm still suspect of that:
```
(venv) x1 ➜  ansible-navigator git:(vol_test) ansible-runner --version
2.1.1
```

LMK, thx

**Comment by cidrblock** [comment]
@dallasspohn Friendly ping :)

**Comment by angelesphillips** [comment]
@cidrblock - I'm on the same team with Dallas. I can confirm that this issue is resolved. I was able to create two custom EEs: one using `ee-supported-rhel8` (version 1.0.1-36) and the other using `ee-minimal-rhel8` (version 1.0.0-70). Both custom EEs displayed playbook output.

Here is output from a custom playbook which uses the `redhat_cop.ah_configuration` collection (added to the custom EE): 
![image](https://user-images.githubusercontent.com/15198401/161849187-18b4b0fc-d80d-49fd-af9e-818ce983bcf8.png)

**Comment by cidrblock** [comment]
@angelesphillips awesome! Thanks for the confirmation.
